package ru.sidey383.ozon.api.performance.objects.answer.campaning;

public enum CampaningState {
    CAMPAIGN_STATE_UNKNOWN,
    CAMPAIGN_STATE_RUNNING,
    CAMPAIGN_STATE_PLANNED,
    CAMPAIGN_STATE_STOPPED,
    CAMPAIGN_STATE_INACTIVE,
    CAMPAIGN_STATE_ARCHIVED,
    CAMPAIGN_STATE_MODERATION_DRAFT,
    CAMPAIGN_STATE_MODERATION_IN_PROGRESS,
    CAMPAIGN_STATE_MODERATION_FAILED,
    CAMPAIGN_STATE_FINISHED
}
